#:kivy 1.11
## IMPORT
#:import Factory kivy.factory.Factory
#:import Color kivy.graphics.Color
#:import Rectangle kivy.graphics.Rectangle
#:import Line kivy.graphics.Line
#:import dp kivy.metrics.dp
#:import ui kvgraphics

# ##>
# ##> BE CAREFUL!
# ##> - The screen is the current root for the screen
# ##> - A widget declared out of a screen has got itself as the root:
# ##>	  so the screen manager is not available to it.
# ##>



