#:kivy 1.11
# MULTI ITEMS WIDGET
#---------------------------------------------------------
# ITEM LIST (box of full list height)
#---------------------------------------------------------
<Item>:

<ItemPart>:
	size_hint: None, 1
	# padding_x: dp(2)
	# Adapt size to text
	halign: 'left'
	valign: 'center'
	text_size: self.size 
	canvas:
		Color:
			rgb: 0.5, 0.5, 0.5, 1
        Line:
            points: self.x, self.y, self.x + self.width, self.y 
            width: 1.2
			